export const copy = {
  zh: {
    title: '手部目標追蹤練習',
    configLabel: '手部目標追蹤設定',
    drill: '追蹤模式',
    drillDesc: '選擇這次要練習的手部追蹤任務。',
    difficulty: '自適應起始難度',
    difficultyDesc: '系統會依命中表現逐步調整速度與目標大小。',
    duration: '訓練時間',
    durationDesc: '設定本次訓練總秒數。',
    hand: '追蹤手',
    handDesc: '可指定左手、右手，或接受畫面中第一隻手。',
    targetSize: '目標大小',
    targetSizeDesc: '放大目標可降低初期負荷。',
    speed: '移動速度',
    speedDesc: '提高速度可增加追蹤與反應需求。',
    privacyTitle: '攝影機畫面只在此裝置分析',
    privacyDesc: '系統不錄影、不上傳畫面；只保存訓練設定與統計結果。',
    loadingTitle: '正在準備手部追蹤',
    loadingCamera: '正在啟動攝影機，請允許瀏覽器使用鏡頭。',
    loadingModel: '正在載入 MediaPipe 手部模型。',
    unsupported: '此瀏覽器不支援攝影機存取，請使用新版 Chrome、Edge 或 Safari。',
    permission: '無法使用攝影機。請允許攝影機權限後再試一次。',
    disconnected: '攝影機已中斷，請確認鏡頭連線後重新開始訓練。',
    initialization: '手部追蹤無法啟動，請確認網路連線後再試一次。',
    errorTitle: '無法開始手部目標追蹤練習',
    openDetails: '開啟錯誤細節',
    cameraPreview: '即時手部攝影機預覽',
    tracking: '已追蹤手部',
    finding: '請把手放入畫面',
    followTarget: '讓手部游標停在目標內',
    target: '目標',
    handCursor: '手部位置',
    timeLeft: '剩餘時間',
    accuracy: '命中率',
    visible: '可追蹤率',
    reps: '完成次數',
    level: '自適應等級',
    hold: '維持',
    resultsTitle: '手部目標追蹤練習完成',
    participant: '訓練使用者',
    interrupted: '中斷維持',
    bestHold: '最佳維持',
    event: '事件',
    result: '結果',
    time: '時間',
    size: '目標大小',
    handAny: '任一手',
    handLeft: '左手',
    handRight: '右手',
    drillNames: {
      bounce: '彈跳球追蹤',
      vertical: '垂直活動範圍',
      horizontal: '水平活動範圍',
      random: '隨機觸達',
    },
    drillDescriptions: {
      bounce: '追蹤在畫面中反彈的球，進行連續手眼協調練習。',
      vertical: '沿垂直路徑上下追蹤目標，練習肩肘控制與垂直活動範圍。',
      horizontal: '沿水平路徑左右追蹤目標，練習跨中線與側向控制。',
      random: '快速移到隨機位置並維持，進行觸達、停止與穩定控制練習。',
    },
    difficultyNames: {
      beginner: '初階',
      intermediate: '中階',
      advanced: '進階',
    },
    success: '成功',
    interruptedLabel: '中斷',
  },
  en: {
    title: 'Hand Target Tracking Practice',
    configLabel: 'Hand Target Tracking Settings',
    drill: 'Tracking Mode',
    drillDesc: 'Choose the hand-tracking task for this session.',
    difficulty: 'Adaptive Start Level',
    difficultyDesc: 'The system adjusts speed and target size based on hit quality.',
    duration: 'Training Duration',
    durationDesc: 'Set the total seconds for this session.',
    hand: 'Tracking Hand',
    handDesc: 'Use the left hand, right hand, or the first visible hand.',
    targetSize: 'Target Size',
    targetSizeDesc: 'Larger targets reduce the initial load.',
    speed: 'Movement Speed',
    speedDesc: 'Higher speed increases tracking and reaction demand.',
    privacyTitle: 'Camera video is analyzed on this device',
    privacyDesc: 'Video is not recorded or uploaded. Only training settings and statistics are saved.',
    loadingTitle: 'Preparing Hand Tracking',
    loadingCamera: 'Starting the camera. Allow browser camera access when prompted.',
    loadingModel: 'Loading the MediaPipe hand model.',
    unsupported: 'This browser does not support camera access. Use a current version of Chrome, Edge, or Safari.',
    permission: 'The camera is unavailable. Allow camera permission and try again.',
    disconnected: 'The camera was disconnected. Check the camera connection and start the training again.',
    initialization: 'Hand tracking could not start. Check the network connection and try again.',
    errorTitle: 'Unable to Start Hand Target Tracking Practice',
    openDetails: 'Open error details',
    cameraPreview: 'Live hand camera preview',
    tracking: 'Hand tracked',
    finding: 'Place your hand in the frame',
    followTarget: 'Keep the hand cursor inside the target',
    target: 'Target',
    handCursor: 'Hand position',
    timeLeft: 'Time Left',
    accuracy: 'Accuracy',
    visible: 'Tracking',
    reps: 'Reps',
    level: 'Adaptive Level',
    hold: 'Hold',
    resultsTitle: 'Hand Target Tracking Practice Complete',
    participant: 'Participant',
    interrupted: 'Interrupted Holds',
    bestHold: 'Best Hold',
    event: 'Event',
    result: 'Result',
    time: 'Time',
    size: 'Target Size',
    handAny: 'Any Hand',
    handLeft: 'Left Hand',
    handRight: 'Right Hand',
    drillNames: {
      bounce: 'Bouncing Ball Tracking',
      vertical: 'Vertical Range',
      horizontal: 'Horizontal Range',
      random: 'Random Reach',
    },
    drillDescriptions: {
      bounce: 'Track a ball as it rebounds around the play field for continuous hand-eye coordination.',
      vertical: 'Follow a target up and down to practice shoulder, elbow, and vertical range control.',
      horizontal: 'Follow a target left and right to practice crossing midline and lateral control.',
      random: 'Move quickly to random target locations and hold steady for reach, stop, and stabilization practice.',
    },
    difficultyNames: {
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
    },
    success: 'Success',
    interruptedLabel: 'Interrupted',
  },
} as const;
