import type { HubLanguage } from '../i18n/HubLanguage';

const copy = {
  zh: {
    header: {
      kicker: 'Developer documentation',
      title: '開發居家練習遊戲',
      intro: '從活動設計、AI 協作、設定介面到安全投稿，依照平台目前實際契約完成一個可審核、可安裝的 jsPsych 8 遊戲。',
      version: '文件對應平台契約 v1',
      scope: '第三方投稿 + 內建遊戲貢獻',
    },
    navigationLabel: '開發文件目錄',
    onThisPage: '文件目錄',
    nav: [
      ['overview', '開始之前'],
      ['quick-start', 'Quick start'],
      ['ai-agent', '安裝 AI Agent'],
      ['architecture', '開發路徑'],
      ['package', '套件結構'],
      ['settings-json', 'settings.json'],
      ['score-json', 'score.json'],
      ['sdk', 'Game SDK'],
      ['research', '研究與內容規範'],
      ['accessibility', '可及性'],
      ['security', '安全限制'],
      ['testing', '測試與驗證'],
      ['prompt-builder', 'AI 結構化提示詞'],
      ['submission', '投稿與版本'],
    ] as const,
    overview: {
      eyebrow: 'Overview',
      title: '先選對開發路徑',
      body: '平台有兩種不同契約。一般開發者提交 HTML／ZIP，由隔離執行站載入 jsPsych 與 Game SDK；倉庫貢獻者則在 Hub 內建立完整的內建遊戲模組。兩者不可混用。',
      routes: [
        {
          number: '01',
          title: '第三方遊戲投稿',
          body: '根目錄必須有 index.html 與 settings.json。遊戲透過 Game SDK 回傳彙總結果；投稿套件目前不讀取 score.json。',
          detail: '適合獨立開發者與單一 HTML／ZIP 遊戲。',
        },
        {
          number: '02',
          title: '內建遊戲貢獻',
          body: '位於 apps/rehabtrainerhub/games/{gameId}/，必須同時擁有 settings.json 與 score.json，並由 OfficialGameShell 註冊。',
          detail: '適合修改本倉庫與共用 Hub 結果畫面。',
        },
      ],
      notice: '本平台提供一般居家練習工具，不是醫療器材開發框架。活動名稱、提示與結果不得宣稱診斷、治療、恢復功能或保證療效。',
    },
    quickStart: {
      eyebrow: 'Quick start',
      title: '以 AI 為主的開發流程',
      intro: '讓 AI Agent 負責盤點契約、產生初版、執行測試與修正；開發者仍須逐項確認活動內容、原始碼、安全限制與結果解釋。',
      steps: [
        ['準備環境', '安裝 Git、Node.js 22 以上與 npm 11。若要貢獻倉庫，先 clone 專案並執行乾淨安裝。'],
        ['啟動 AI Agent', '在專案或遊戲資料夾執行 Codex，先要求它閱讀 AGENTS.md、此文件與實際 schema，再開始寫程式。'],
        ['先寫活動規格', '定義活動需求、刺激參數、每回合流程、停止方式、輸入裝置、彙總指標與限制，暫時不要產生程式碼。'],
        ['產生並驗證', '建立 index.html、settings.json 與遊戲原始碼；倉庫內建遊戲再建立 score.json，執行對應測試並人工操作。'],
        ['送審前複核', '確認雙語、鍵盤／觸控、無外連、無個資、未混淆、沒有自行打包 jsPsych 或 SDK，再建立新版本投稿。'],
      ],
      installTitle: '倉庫開發環境',
      installNote: '第三方投稿者可只製作遊戲資料夾；若要使用倉庫測試與範例，依下列流程準備完整環境。',
    },
    aiAgent: {
      eyebrow: 'AI-assisted development',
      title: '安裝並啟動 Codex',
      body: 'OpenAI 官方 Codex CLI 可在終端機讀取、修改與執行目前資料夾中的程式碼。安裝方式可能隨平台更新，請以官方安裝頁的作業系統分頁為準。',
      officialLink: '開啟官方 Codex CLI 安裝指南',
      npmTitle: 'npm 安裝方式',
      runTitle: '在遊戲或倉庫資料夾啟動',
      notes: [
        '首次執行 codex 時依畫面使用 ChatGPT 帳號或可用的驗證方式登入。',
        '先建立 Git checkpoint；只授權 Agent 存取這個專案資料夾。',
        '把本頁「AI 結構化提示詞」產生的內容貼給 Agent，再要求它先回報缺少的規格。',
        'AI 產生的研究敘述、引用、分數公式與無障礙行為都必須由人員查核。',
      ],
    },
    architecture: {
      eyebrow: 'Architecture',
      title: '平台如何載入遊戲',
      flow: ['Hub 產生設定表單', '驗證 settings', '隔離 iframe', 'SDK 私有通道', '彙總結果', 'Hub 儲存紀錄'],
      body: 'Hub 只負責設定表單、容器、登入紀錄與離開流程。第三方程式在獨立網域的 sandbox="allow-scripts" iframe 執行，無法讀取主平台 Cookie；平台以 MessageChannel 傳送已驗證設定與接收彙總結果。',
      boundaryTitle: '責任邊界',
      boundaries: [
        ['遊戲擁有', 'jsPsych timeline、自訂 plugin、renderer／canvas lifecycle、刺激規則、回饋與彙總公式。'],
        ['Hub 擁有', '設定表單、語言、容器、結果外框、登入狀態、紀錄寫入與離開操作。'],
        ['執行站擁有', 'CSP、iframe 隔離、版本化 runtime、PWA scope、撤回版本與私有通訊橋樑。'],
      ],
    },
    package: {
      eyebrow: 'Package contract',
      title: '第三方套件結構',
      body: 'ZIP 的 index.html 與 settings.json 必須直接位於根目錄。所有圖片、音效、字型、CSS、自訂 plugin 與程式碼都放在套件內，路徑只能使用 ASCII 字母、數字、點、底線、連字號與斜線。',
      rules: [
        '上傳檔最多 12 MiB；解壓縮後最多 24 MiB；單檔最多 8 MiB。',
        '最多 192 個檔案；可執行與文字原始碼合計最多 4 MiB。',
        '提交可閱讀、未壓縮、未混淆的原始碼；單行不得超過 5,000 字元。',
        '不要加入 manifest、service worker、jsPsych 或 TrainerHub Game SDK；平台會提供。',
        '第三方套件不需要 score.json；結果由 SDK summarize() 回傳。',
      ],
    },
    settings: {
      eyebrow: 'Configuration schema',
      title: 'settings.json：由 Hub 產生設定介面',
      body: 'settings.json 是兩條開發路徑都需要的宣告。Hub 在建立 iframe 前驗證它，並將使用者選擇的值傳給遊戲。遊戲內不得再複製一份設定畫面。',
      rules: [
        'schemaVersion 固定為 1，gameId 必須與遊戲 slug／資料夾名稱完全相同。',
        '文字必須同時提供 zh-TW 與 en；最多 16 個 section、64 個欄位、64 KiB JSON。',
        '支援 slider、list、checkbox、color。slider 的 default 必須落在 min／max 且符合 step。',
        'key 以小寫英文字母開頭，可含英數、點、底線與連字號；禁止 auth、email、name、token、user 等敏感名稱。',
        '只放本次活動需要的刺激與操作參數，不放自由文字、網址、帳號或健康資料。',
      ],
      fieldTitle: '欄位選擇',
      fields: [
        ['slider', '有上下界與可解釋步距的數值，例如回合數或刺激呈現時間。'],
        ['list', '有限且互斥的條件；不同條件會改變活動需求時，應在結果解釋中分開比較。'],
        ['checkbox', '可獨立開關的非必要功能，例如聲音回饋。'],
        ['color', '六位十六進位色碼；不可用來編碼診斷或能力等級。'],
      ],
    },
    score: {
      eyebrow: 'Built-in games only',
      title: 'score.json：內建遊戲的結果投影',
      body: 'score.json 僅用於倉庫內 40 個內建遊戲。它告訴 Hub 如何把遊戲結果中的數值／布林欄位投影成共用表格、圖表與摘要；它不包含計分公式或可執行 renderer。',
      externalNotice: '第三方 HTML／ZIP 投稿目前不解析 score.json。請在 Game SDK 的 summarize() 回傳 score、durationMs、trialCount 與 metrics。',
      rules: [
        'schema 固定為 rehab-trainer.game-score/v1；gameId 與 settings.json 相同。',
        'columns 與 summary 各 1–12 欄，每欄提供 key、zh／en label 與 sources；unit、total 可省略。',
        'presentation 指定 1–4 個主要摘要、最多 4 個品質／情境欄位、預設每回合指標與 line／bar 圖。',
        '只接受有限數值、布林或 null；最多 4,000 回合、450 KiB，數值絕對值不得超過 10¹²。',
        '不同構念不得合併成同一來源；反應時間、正確率、完成量與品質指標應分欄並保留單位。',
      ],
    },
    sdk: {
      eyebrow: '@rehab-trainer/game-sdk',
      title: 'Game SDK 與 jsPsych 生命週期',
      body: '第三方遊戲必須使用平台提供的 jsPsych 8.2.3 與 Game SDK 0.1.0。SDK 會等待私有 MessagePort 與設定，處理 pause／resume／exit，並在 timeline 結束時驗證彙總結果。',
      runtimeTitle: '固定 runtime 路徑',
      resultTitle: 'summarize() 可回傳',
      resultRules: [
        'status：completed 或 aborted。',
        'score：有限數值；durationMs：0 到 24 小時的安全整數。',
        'trialCount：0 到 100,000 的安全整數。',
        'metrics：最多 512 個數值、布林或 null；總結果最多 16,000 UTF-8 bytes。',
        '禁止姓名、帳號、email、participant、session、token、原始 trial、影像、聲音或動作軌跡。',
      ],
      lifecycleTitle: '實作重點',
      lifecycle: [
        '不要在頂層 await RunTrainerHubJsPsychGame()；iframe load 後才會收到私有通道。',
        '自訂 canvas／renderer 應放在單一 jsPsych plugin 內，並在 finish 或 abort 路徑解除 listener 與釋放資源。',
        'timeline(settings) 只使用已驗證設定；summarize(jsPsych, settings) 只產生非識別彙總值。',
      ],
    },
    research: {
      eyebrow: 'OT & research checklist',
      title: '先定義活動，再定義分數',
      body: '一個看似簡單的遊戲可能同時要求視覺搜尋、持續注意、反應抑制、動作速度與裝置操作。文件與結果只能描述實際任務，不可由遊戲表現推論疾病、日常功能或治療效果。',
      cards: [
        ['活動構念', '寫出主要與次要活動需求，說明刺激、反應與成功條件如何對應；避免只用「訓練大腦」等籠統說法。'],
        ['刺激與劑量', '記錄回合數、呈現時間、間隔、刺激大小、隨機化、練習回合與停止條件；把可調值放進 settings.json。'],
        ['結果定義', '逐一說明每個值的公式、單位、分母、遺漏值與極端值處理；正確率與反應時間不可混成未說明的單一分數。'],
        ['限制與混淆', '揭露輸入裝置、螢幕、網路瀏覽器、熟悉度、疲勞、視聽與動作需求可能影響結果。'],
        ['證據層級', '優先引用原始研究、同儕審查文獻或官方方法文件，核對實際版本；參考方法不等於具備同等信效度。'],
        ['用語邊界', '使用練習、活動、刺激參數、當次紀錄與換算參考值；不宣稱診斷、處方、治療、恢復功能或保證效果。'],
      ],
      minimumTitle: '建議隨程式碼保存的活動規格',
      minimum: ['目標活動需求與非目標需求', '適用輸入裝置與操作姿勢', '每回合程序與隨機化方式', '設定值範圍及選擇理由', '結果公式、單位與限制', '練習／中止／錯誤處理', '雙語可見文字', '來源與最後查核日期'],
    },
    accessibility: {
      eyebrow: 'Accessibility',
      title: '讓操作方式可被替代',
      rules: [
        '使用 main、h1–h3、p、button、ol／ul 等語意元素；不要用 div 模擬按鈕。',
        '所有操作可由鍵盤完成，焦點清楚可見；不要只靠顏色、聲音或動態表達狀態。',
        '指標目標至少 44 × 44 CSS px，避免要求精細拖曳；提供等效點按或鍵盤方式。',
        '支援 prefers-reduced-motion；閃爍不得超過安全頻率，時間限制應可在活動規格允許時調整。',
        '指示文字採短句並在操作前呈現；錯誤回饋說明發生什麼與下一步，不責備使用者。',
        '測試 200% 縮放、手機直／橫向、觸控、鍵盤與螢幕閱讀器基本流程。',
      ],
    },
    security: {
      eyebrow: 'Security gate',
      title: '會被自動阻擋的行為',
      body: '掃描只是初步分類，不是安全邊界。通過掃描後仍會在無敏感憑證的隔離環境進行原始碼查核與人工試玩。',
      groups: [
        ['網路與外部內容', 'fetch、XHR、WebSocket、EventSource、sendBeacon、WebRTC、http(s) URL、CSS @import。'],
        ['導頁與瀏覽器狀態', 'document.cookie、location、window.top、window.open、history navigation、表單與超連結。'],
        ['動態與背景執行', 'eval、Function、atob／btoa、Reflective access、ServiceWorker、Worker、SharedWorker、importScripts。'],
        ['巢狀內容', 'iframe、frame、object、embed、base、meta refresh 與動態 document.write。'],
      ],
    },
    testing: {
      eyebrow: 'Verification',
      title: '測試與送審前檢核',
      thirdPartyTitle: '第三方遊戲',
      thirdParty: [
        '以可閱讀原始碼人工檢查所有 script、事件 listener 與資源路徑。',
        '使用鍵盤、滑鼠／觸控完成整個 timeline，測試 pause、resume、exit 與重複開始。',
        '確認 summarize() 在正常完成、無作答與中止時都只回傳合法彙總值。',
        '上傳後查看自動掃描 finding；阻擋項目必須修正後以新 semver 版本重送。',
      ],
      repoTitle: '倉庫貢獻者',
      repoNote: '改動內建遊戲、共用設定或結果契約時，至少執行下列 gate；涉及 entrypoint／renderer／fullscreen 時不可省略 build:hub。',
    },
    prompt: {
      eyebrow: 'Prompt builder',
      title: '產生可交給 AI Agent 的結構化提示詞',
      body: '先填寫活動意圖與操作條件。產生的提示詞會鎖定平台契約、研究界線、安全與驗證輸出，適合直接貼入 Codex。',
      fields: {
        route: '開發路徑',
        title: '遊戲暫定名稱',
        target: '主要活動需求',
        interaction: '每回合互動',
        input: '輸入方式',
        session: '回合／時間設計',
        metrics: '預計彙總指標',
        evidence: '參考依據與限制',
      },
      placeholders: {
        title: '例如：目標點擊練習',
        target: '例如：視覺搜尋與指標點按',
        interaction: '描述刺激出現、使用者反應、正確／錯誤與回饋',
        session: '例如：5 回合練習 + 20 回合活動，可調刺激間隔',
        metrics: '例如：正確次數、遺漏次數、反應時間中位數',
        evidence: '列出文獻、方法來源、尚未驗證處與可能混淆因素',
      },
      routes: [['third-party', '第三方 HTML／ZIP 投稿'], ['built-in', '倉庫內建遊戲']] as const,
      inputs: [['pointer', '滑鼠／觸控'], ['keyboard', '鍵盤'], ['both', '滑鼠／觸控 + 鍵盤']] as const,
      generate: '更新提示詞',
      copy: '複製提示詞',
      copied: '已複製',
      outputLabel: '產生的 AI Agent 提示詞',
    },
    submission: {
      eyebrow: 'Developer workspace',
      signedOutTitle: '登入後投稿遊戲',
      signedOutBody: '使用右上角帳戶按鈕登入後，即可上傳 HTML／ZIP、查看掃描結果與人工審核進度。閱讀文件與產生提示詞不需要登入。',
      uploadTitle: '上傳新版本',
      slug: '遊戲識別碼',
      slugHelp: '只能使用小寫英文字母、數字與連字號；後續版本沿用同一識別碼。',
      displayName: '顯示名稱',
      developerName: '公開開發者名稱',
      developerHelp: '此名稱會顯示在公開遊戲大廳；不會自動公開帳戶姓名或電子郵件。',
      summary: '內容摘要',
      trainer: '遊戲大分類',
      trainerPlaceholder: '請選擇 motor、mouth、brain 或 vision',
      trainerHelp: '此分類會決定設定畫面的主題顏色。',
      category: '大廳篩選標籤',
      categoryPlaceholder: '請選擇 filter panel 對應項目',
      categoryHelp: '只會列出所選大分類可使用的篩選項目。',
      version: '版本',
      jsPsychVersion: 'jsPsych 版本',
      jsPsychHelp: '由隔離執行站固定提供，不需放入上傳套件。',
      capabilities: '需要的基本能力',
      capabilityLabels: { audio: '播放音效', fullscreen: '全螢幕', keyboard: '鍵盤輸入', pointer: '滑鼠／觸控指標' },
      package: 'HTML 或 ZIP 遊戲包',
      packageLimit: '上限 12 MB',
      confirmation: '我確認原始碼未混淆、所有遊戲資產皆在包內，且不會嘗試對外通訊、讀取 Cookie 或蒐集個資。',
      submitting: '掃描並上傳中…',
      submit: '掃描並送審',
      releasesEyebrow: 'Submissions',
      releasesTitle: '我的投稿',
      loading: '正在載入投稿…',
      empty: '尚未投稿遊戲。',
      developer: '公開開發者',
      trainerLabel: '大分類',
      categoryLabel: '篩選標籤',
      reviewNote: '審核備註',
      fileCount: '個檔案',
      counts: (games: number, releases: number) => `${games} 個遊戲、${releases} 個版本`,
      errors: {
        load: '目前無法載入投稿。',
        file: '請選擇 12 MB 以下的 HTML 或 ZIP 檔案。',
        incomplete: '請選擇遊戲大分類與篩選標籤、上傳檔案，並確認原始碼未混淆且不含外部通訊。',
        submit: '目前無法送出遊戲包。',
      },
      messages: {
        blocked: (count: number) => `已完成掃描，但偵測到 ${count} 個阻擋項目。`,
        pending: '已安全存入隔離區並送交人工審核。',
      },
      status: {
        blocked: '自動掃描阻擋', pending_review: '等待人工審核', publishing: '正在發布', approved: '已核准上架', rejected: '未通過審核', revoked: '已緊急下架',
      },
    },
  },
  en: {
    header: {
      kicker: 'Developer documentation',
      title: 'Build a home-practice game',
      intro: 'Follow the platform’s current contracts from activity design and AI collaboration through configuration, security review, and submission of an installable jsPsych 8 game.',
      version: 'Platform contract v1',
      scope: 'Third-party submissions + built-in contributions',
    },
    navigationLabel: 'Developer documentation contents',
    onThisPage: 'Documentation',
    nav: [
      ['overview', 'Before you start'],
      ['quick-start', 'Quick start'],
      ['ai-agent', 'Install an AI agent'],
      ['architecture', 'Development paths'],
      ['package', 'Package structure'],
      ['settings-json', 'settings.json'],
      ['score-json', 'score.json'],
      ['sdk', 'Game SDK'],
      ['research', 'Research & content'],
      ['accessibility', 'Accessibility'],
      ['security', 'Security limits'],
      ['testing', 'Test & verify'],
      ['prompt-builder', 'Structured AI prompt'],
      ['submission', 'Submit & version'],
    ] as const,
    overview: {
      eyebrow: 'Overview',
      title: 'Choose the correct development path',
      body: 'The platform has two distinct contracts. General developers submit HTML/ZIP packages that load jsPsych and the Game SDK in the isolated runner. Repository contributors build a complete first-party game module inside the Hub. Do not mix the two contracts.',
      routes: [
        {
          number: '01',
          title: 'Third-party game submission',
          body: 'The package root requires index.html and settings.json. The game returns aggregate results through the Game SDK; submitted packages do not currently use score.json.',
          detail: 'For independent developers and portable HTML/ZIP games.',
        },
        {
          number: '02',
          title: 'Built-in game contribution',
          body: 'Lives at apps/rehabtrainerhub/games/{gameId}/, owns both settings.json and score.json, and registers them with OfficialGameShell.',
          detail: 'For repository changes using the shared Hub result view.',
        },
      ],
      notice: 'This platform provides general home-practice tools; it is not a medical-device development framework. Names, instructions, and results must not claim diagnosis, treatment, functional recovery, or guaranteed outcomes.',
    },
    quickStart: {
      eyebrow: 'Quick start',
      title: 'An AI-first development loop',
      intro: 'Use an AI agent to inspect contracts, draft the first implementation, run tests, and correct failures. A developer must still verify the activity content, source code, safety limits, and interpretation of every result.',
      steps: [
        ['Prepare the environment', 'Install Git, Node.js 22 or later, and npm 11. Repository contributors should clone the project and perform a clean install.'],
        ['Start the AI agent', 'Run Codex in the project or game folder. Ask it to read AGENTS.md, this guide, and the actual schemas before writing code.'],
        ['Specify the activity first', 'Define task demands, stimulus parameters, each trial, exit behavior, input devices, aggregate metrics, and limitations before asking for code.'],
        ['Generate and verify', 'Create index.html, settings.json, and game source. Built-in games also need score.json. Run the relevant tests and complete a hands-on playthrough.'],
        ['Review before submission', 'Check both languages, keyboard and touch, network isolation, data minimization, readable source, and platform-provided runtimes before submitting a new version.'],
      ],
      installTitle: 'Repository development environment',
      installNote: 'Third-party developers may work in a standalone game folder. Use the full repository setup when you need its examples and validation gates.',
    },
    aiAgent: {
      eyebrow: 'AI-assisted development',
      title: 'Install and start Codex',
      body: 'The official OpenAI Codex CLI can inspect, edit, and run code in the current folder from a terminal. Installation methods can change; use the operating-system tab in the official guide as the source of truth.',
      officialLink: 'Open the official Codex CLI installation guide',
      npmTitle: 'Install with npm',
      runTitle: 'Start in the game or repository folder',
      notes: [
        'On the first codex run, follow the prompt to sign in with ChatGPT or another available authentication method.',
        'Create a Git checkpoint first and grant the agent access only to this project folder.',
        'Paste the output from the Structured AI prompt section below, then ask the agent to report missing specifications before implementation.',
        'A person must verify AI-generated research statements, citations, scoring formulas, and accessibility behavior.',
      ],
    },
    architecture: {
      eyebrow: 'Architecture',
      title: 'How the platform loads a game',
      flow: ['Hub renders settings', 'Validate settings', 'Isolated iframe', 'Private SDK channel', 'Aggregate result', 'Hub stores record'],
      body: 'The Hub owns configuration, containment, account records, and exit flow. Third-party code runs on a separate origin in a sandbox="allow-scripts" iframe and cannot read Hub cookies. A MessageChannel carries validated settings and aggregate results.',
      boundaryTitle: 'Ownership boundaries',
      boundaries: [
        ['The game owns', 'The jsPsych timeline, custom plugins, renderer/canvas lifecycle, stimulus rules, feedback, and aggregate formulas.'],
        ['The Hub owns', 'The settings form, language, container, result shell, authentication state, record persistence, and exit controls.'],
        ['The runner owns', 'CSP, iframe isolation, versioned runtimes, PWA scope, revocation behavior, and the private communication bridge.'],
      ],
    },
    package: {
      eyebrow: 'Package contract',
      title: 'Third-party package structure',
      body: 'index.html and settings.json must sit directly at the ZIP root. Include every image, sound, font, stylesheet, custom plugin, and source file in the package. Paths may contain only ASCII letters, numbers, dots, underscores, hyphens, and slashes.',
      rules: [
        'Upload size: 12 MiB; expanded size: 24 MiB; individual file: 8 MiB.',
        'At most 192 files and 4 MiB of executable plus text source.',
        'Submit readable, unminified, unobfuscated source with no line longer than 5,000 characters.',
        'Do not add a manifest, service worker, jsPsych, or the TrainerHub Game SDK; the platform supplies them.',
        'Third-party packages do not need score.json; return results from SDK summarize().',
      ],
    },
    settings: {
      eyebrow: 'Configuration schema',
      title: 'settings.json: Hub-generated configuration',
      body: 'Both development paths use settings.json. The Hub validates it before creating the iframe and sends the selected values to the game. Do not duplicate this settings screen inside the game.',
      rules: [
        'schemaVersion is 1. gameId must exactly match the submitted slug or built-in folder name.',
        'Every visible string requires zh-TW and en. Limits: 16 sections, 64 fields, and 64 KiB of JSON.',
        'Supported controls are slider, list, checkbox, and color. Slider defaults must align with min, max, and step.',
        'Keys start with a lowercase letter and may contain letters, numbers, dots, underscores, or hyphens. Sensitive names such as auth, email, name, token, and user are rejected.',
        'Include only stimulus and interaction parameters for this session—never free text, URLs, account data, or health information.',
      ],
      fieldTitle: 'Choosing a control',
      fields: [
        ['slider', 'A bounded number with a meaningful step, such as trial count or stimulus duration.'],
        ['list', 'Finite, mutually exclusive conditions. Analyze separately when options change task demands.'],
        ['checkbox', 'An independent optional feature, such as sound feedback.'],
        ['color', 'A six-digit hex color. Never use color to encode a diagnosis or ability level.'],
      ],
    },
    score: {
      eyebrow: 'Built-in games only',
      title: 'score.json: project built-in results',
      body: 'score.json is used only by the repository’s 40 built-in games. It tells the Hub how numeric and boolean game results map to shared tables, charts, and summaries. It contains neither scoring formulas nor executable renderers.',
      externalNotice: 'Third-party HTML/ZIP submissions do not currently parse score.json. Return score, durationMs, trialCount, and metrics from the Game SDK summarize() callback.',
      rules: [
        'schema is rehab-trainer.game-score/v1. gameId matches settings.json.',
        'columns and summary each contain 1–12 fields with key, zh/en label, and sources; unit and total are optional.',
        'presentation selects 1–4 primary summaries, up to 4 quality/context fields, a default round metric, and a line or bar chart.',
        'Values are finite numbers, booleans, or null. Limits: 4,000 rounds, 450 KiB, and an absolute value no greater than 10¹².',
        'Do not merge unlike constructs into one source. Keep reaction time, accuracy, quantity, and quality in distinct fields with units.',
      ],
    },
    sdk: {
      eyebrow: '@rehab-trainer/game-sdk',
      title: 'Game SDK and the jsPsych lifecycle',
      body: 'Third-party games must use platform-hosted jsPsych 8.2.3 and Game SDK 0.1.0. The SDK waits for the private MessagePort and settings, handles pause/resume/exit, and validates the aggregate result after the timeline finishes.',
      runtimeTitle: 'Fixed runtime paths',
      resultTitle: 'summarize() may return',
      resultRules: [
        'status: completed or aborted.',
        'score: a finite number; durationMs: a safe integer from 0 through 24 hours.',
        'trialCount: a safe integer from 0 through 100,000.',
        'metrics: at most 512 finite numbers, booleans, or null values; the full result is limited to 16,000 UTF-8 bytes.',
        'Never include names, accounts, email, participant or session identifiers, tokens, raw trials, images, audio, or motion traces.',
      ],
      lifecycleTitle: 'Implementation details',
      lifecycle: [
        'Do not top-level await RunTrainerHubJsPsychGame(); the private channel arrives after the iframe load event.',
        'Keep a custom canvas or renderer inside one jsPsych plugin, and remove listeners and release resources in finish and abort paths.',
        'timeline(settings) consumes only validated settings; summarize(jsPsych, settings) produces only non-identifying aggregates.',
      ],
    },
    research: {
      eyebrow: 'OT & research checklist',
      title: 'Define the activity before the score',
      body: 'A simple-looking game can require visual search, sustained attention, inhibition, movement speed, and device operation at the same time. Documentation and results may describe only the actual task; do not infer disease, daily function, or treatment effects from game performance.',
      cards: [
        ['Activity constructs', 'Name primary and secondary task demands and explain how stimuli, responses, and success criteria relate to them. Avoid vague claims such as “train the brain.”'],
        ['Stimuli and dose', 'Record trial count, exposure time, interval, stimulus size, randomization, practice trials, and stopping conditions. Put adjustable values in settings.json.'],
        ['Outcome definitions', 'Document each formula, unit, denominator, missing-value rule, and outlier rule. Do not combine accuracy and response time into an unexplained score.'],
        ['Limits and confounds', 'Disclose input device, display, browser, familiarity, fatigue, sensory demands, and movement demands that may affect results.'],
        ['Evidence level', 'Prefer original research, peer-reviewed literature, and official method documentation, and verify the implemented version. Referencing a method does not establish equivalent reliability or validity.'],
        ['Language boundary', 'Use practice, activity, stimulus parameter, session record, and conversion reference. Do not claim diagnosis, prescription, treatment, functional recovery, or guaranteed effects.'],
      ],
      minimumTitle: 'Minimum activity specification to keep with the code',
      minimum: ['Target and non-target task demands', 'Supported input devices and posture', 'Trial procedure and randomization', 'Setting ranges and rationale', 'Result formulas, units, and limitations', 'Practice, exit, and error handling', 'Visible copy in both languages', 'Sources and last verification date'],
    },
    accessibility: {
      eyebrow: 'Accessibility',
      title: 'Provide equivalent ways to operate',
      rules: [
        'Use semantic main, h1–h3, p, button, ol, and ul elements. Never emulate buttons with div elements.',
        'Make every action keyboard-operable with visible focus. Do not communicate state through color, sound, or motion alone.',
        'Use pointer targets at least 44 × 44 CSS px. Avoid precision dragging or provide an equivalent tap/keyboard method.',
        'Respect prefers-reduced-motion. Keep flashing within safe limits and allow timing adjustments when the activity specification permits.',
        'Use short instructions shown before interaction. Error feedback explains what happened and the next action without blaming the user.',
        'Test 200% zoom, mobile portrait and landscape, touch, keyboard, and the basic screen-reader flow.',
      ],
    },
    security: {
      eyebrow: 'Security gate',
      title: 'Behavior blocked by automated review',
      body: 'Scanning is triage, not the security boundary. Passing packages still undergo source review and hands-on testing in an isolated environment without sensitive credentials.',
      groups: [
        ['Network and remote content', 'fetch, XHR, WebSocket, EventSource, sendBeacon, WebRTC, http(s) URLs, and CSS @import.'],
        ['Navigation and browser state', 'document.cookie, location, window.top, window.open, history navigation, forms, and links.'],
        ['Dynamic and background execution', 'eval, Function, atob/btoa, reflective access, ServiceWorker, Worker, SharedWorker, and importScripts.'],
        ['Nested content', 'iframe, frame, object, embed, base, meta refresh, and dynamic document.write.'],
      ],
    },
    testing: {
      eyebrow: 'Verification',
      title: 'Test and pre-submission review',
      thirdPartyTitle: 'Third-party games',
      thirdParty: [
        'Review every script, event listener, and asset path in readable source.',
        'Complete the full timeline with keyboard and pointer/touch; test pause, resume, exit, and repeated starts.',
        'Verify summarize() returns only valid aggregates on completion, no-response sessions, and aborts.',
        'Review scanner findings after upload. Fix blocking items and resubmit with a new semantic version.',
      ],
      repoTitle: 'Repository contributors',
      repoNote: 'For built-in games or shared settings/result contracts, run at least these gates. Changes involving an entry point, renderer, or fullscreen flow also require build:hub.',
    },
    prompt: {
      eyebrow: 'Prompt builder',
      title: 'Generate a structured prompt for an AI agent',
      body: 'Describe the activity intent and operating conditions first. The generated prompt locks in platform contracts, research boundaries, safety requirements, and verification output and can be pasted directly into Codex.',
      fields: {
        route: 'Development path',
        title: 'Working game title',
        target: 'Primary task demands',
        interaction: 'Interaction in each trial',
        input: 'Input method',
        session: 'Trials and timing',
        metrics: 'Planned aggregate metrics',
        evidence: 'Evidence and limitations',
      },
      placeholders: {
        title: 'Example: Target selection practice',
        target: 'Example: visual search and pointer selection',
        interaction: 'Describe stimulus onset, response, correct/error behavior, and feedback',
        session: 'Example: 5 practice + 20 activity trials with adjustable intervals',
        metrics: 'Example: correct, omissions, and median response time',
        evidence: 'List sources, method references, unvalidated assumptions, and confounds',
      },
      routes: [['third-party', 'Third-party HTML/ZIP submission'], ['built-in', 'Repository built-in game']] as const,
      inputs: [['pointer', 'Pointer/touch'], ['keyboard', 'Keyboard'], ['both', 'Pointer/touch + keyboard']] as const,
      generate: 'Update prompt',
      copy: 'Copy prompt',
      copied: 'Copied',
      outputLabel: 'Generated AI agent prompt',
    },
    submission: {
      eyebrow: 'Developer workspace',
      signedOutTitle: 'Sign in to submit a game',
      signedOutBody: 'Use the account button in the upper-right corner to sign in, upload HTML/ZIP, and review scan and approval status. The documentation and prompt builder are available without signing in.',
      uploadTitle: 'Upload a new version',
      slug: 'Game identifier',
      slugHelp: 'Lowercase letters, numbers, and hyphens only. Later versions reuse the same identifier.',
      displayName: 'Display name',
      developerName: 'Public developer name',
      developerHelp: 'Shown in the public game lobby. Your account name and email are not published automatically.',
      summary: 'Content summary',
      trainer: 'Game category',
      trainerPlaceholder: 'Select motor, mouth, brain, or vision',
      trainerHelp: 'This category determines the settings theme color.',
      category: 'Lobby filter tag',
      categoryPlaceholder: 'Select a matching filter-panel item',
      categoryHelp: 'Only tags supported by the selected category are listed.',
      version: 'Version',
      jsPsychVersion: 'jsPsych version',
      jsPsychHelp: 'Fixed by the isolated runner; do not include it in the package.',
      capabilities: 'Required basic capabilities',
      capabilityLabels: { audio: 'Audio playback', fullscreen: 'Fullscreen', keyboard: 'Keyboard input', pointer: 'Pointer/touch input' },
      package: 'HTML or ZIP game package',
      packageLimit: '12 MB maximum',
      confirmation: 'I confirm that the source is unobfuscated, all game assets are local, and the game does not attempt external communication, cookie access, or personal-data collection.',
      submitting: 'Scanning and uploading…',
      submit: 'Scan and submit',
      releasesEyebrow: 'Submissions',
      releasesTitle: 'My submissions',
      loading: 'Loading submissions…',
      empty: 'No games submitted yet.',
      developer: 'Public developer',
      trainerLabel: 'Category',
      categoryLabel: 'Filter tag',
      reviewNote: 'Review note',
      fileCount: 'files',
      counts: (games: number, releases: number) => `${games} games, ${releases} releases`,
      errors: {
        load: 'Submissions cannot be loaded right now.',
        file: 'Select an HTML or ZIP file no larger than 12 MB.',
        incomplete: 'Select a game category and filter tag, upload a package, and confirm readable source with no external communication.',
        submit: 'The game package cannot be submitted right now.',
      },
      messages: {
        blocked: (count: number) => `Scanning finished with ${count} blocking findings.`,
        pending: 'The package is quarantined safely and queued for human review.',
      },
      status: {
        blocked: 'Blocked by scan', pending_review: 'Awaiting human review', publishing: 'Publishing', approved: 'Approved', rejected: 'Review failed', revoked: 'Revoked',
      },
    },
  },
} as const;

export function GetDeveloperCopy(language: HubLanguage) {
  return copy[language];
}
